apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-repl

# Points to the directories containing the child kustomizations
resources:
  - ../dev

configMapGenerator:
- name: mysql-config
  behavior: replace
  files:
    - my.cnf 

secretGenerator:
- name: mysql-secret
  behavior: replace
  envs:
  - env.secret




