apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  strategy:
    type: Recreate # Ensures old pod stops before new pod starts to unbind PVC
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      serviceAccountName: minio-sa
      automountServiceAccountToken: false
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ROOT_PASSWORD
          resources:
            requests:
              ephemeral-storage: "1Gi"
              memory: "512Mi"
              cpu: "250m"
            limits:
              ephemeral-storage: "2Gi"
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: storage
              mountPath: "/data"
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 30              
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
