apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Points to the directories containing the child kustomizations
resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - service-account.yaml
  - service-lb.yaml

# Transformations applied to ALL children
labels:
- pairs:
    product: infra
    env: base

