apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
  labels:
    app: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
