apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbao-deployment
  labels:
    app: openbao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      containers:
      - name: openbao
        image: openbao/openbao:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: openbao-secrets   
        args: ["server", "-dev"]
        ports:
        - containerPort: 8200
          name: http
